# Generated by Django 5.2.4 on 2026-02-21 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=255)),
                ("conversion_rate", models.FloatField(default=1.0)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
            ],
            options={
                "db_table": "tbl_currency",
            },
        ),
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("group_id", models.IntegerField()),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_age_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_age_group",
            },
        ),
        migrations.CreateModel(
            name="AssignedTherapist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "therapist_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "therapist_name",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("assigned_on", models.DateTimeField()),
                ("changed_on", models.DateTimeField(blank=True, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(1, "Assigned"), (2, "Changed")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_therapists_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_therapist_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_assigned_therapist",
            },
        ),
        migrations.CreateModel(
            name="BestDoctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("discription", models.TextField(blank=True, null=True)),
                ("image_file", models.CharField(blank=True, max_length=255, null=True)),
                ("speciality", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_best_doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_best_doctor",
            },
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=255)),
                ("contact_no", models.CharField(blank=True, max_length=32, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("experience", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Accept"),
                            (2, "Reject"),
                            (3, "Added"),
                        ],
                        default=1,
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contact_forms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_contact_form",
            },
        ),
        migrations.CreateModel(
            name="Disclaimer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("discription", models.TextField(blank=True, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_disclaimers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_disclaimer",
            },
        ),
        migrations.CreateModel(
            name="DoctorReason",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_doctor_reasons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_doctor_reason",
            },
        ),
        migrations.CreateModel(
            name="DoctorRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_doctor_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_doctor_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_requests",
                        to="core.doctorreason",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_doctor_request",
            },
        ),
        migrations.CreateModel(
            name="EmergencyResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256, unique=True)),
                ("contact_no", models.CharField(max_length=32)),
                (
                    "alternate_contact_no",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("timings", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_emergency_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_emergency_resource",
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("model_type", models.CharField(max_length=128)),
                ("model_id", models.IntegerField()),
                ("user_ip", models.CharField(blank=True, max_length=255, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_feed",
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("size", models.IntegerField(default=0)),
                ("key", models.CharField(max_length=255)),
                ("model_type", models.CharField(max_length=128)),
                ("model_id", models.IntegerField(blank=True, null=True)),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[(0, "File"), (1, "SymbolicLink"), (2, "URL")],
                        default=0,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_file",
            },
        ),
        migrations.CreateModel(
            name="HomeContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("discription", models.TextField(blank=True, null=True)),
                ("image_file", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Main Content"),
                            (2, "Section First"),
                            (3, "Section Second"),
                            (4, "Section Third"),
                            (5, "Section Fourth"),
                        ],
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_home_contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_home_content",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=64)),
                ("subscribed_plan_id", models.IntegerField(blank=True, null=True)),
                ("to_email", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "razorpay_invoice_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Subscription Invoice"),
                            (2, "Video Plan Invoice"),
                        ],
                        default=1,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="core.file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_invoice",
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_ip", models.CharField(max_length=255)),
                ("user_agent", models.CharField(max_length=255)),
                (
                    "failer_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("login_time", models.DateTimeField(blank=True, null=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(choices=[(0, "Failed"), (1, "Success")]),
                ),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[(0, "Web"), (1, "Ajax"), (2, "API")]
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_login_history",
            },
        ),
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "role_type",
                    models.SmallIntegerField(
                        choices=[(1, "User"), (2, "Therapist"), (3, "Both")]
                    ),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Pending"),
                            (2, "Sent"),
                            (3, "Failed"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "type_id",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Subscribed Users"),
                            (2, "Not Subscribed Users"),
                            (3, "Expired Subscription Users"),
                            (4, "Therapist"),
                            (5, "Everyone"),
                        ],
                        null=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_push_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_push_notification",
            },
        ),
        migrations.CreateModel(
            name="RefundLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("booking_id", models.IntegerField(blank=True, null=True)),
                ("credit", models.IntegerField(default=0)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_logs_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_refund_log",
            },
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[
                            (0, "String"),
                            (1, "Boolean"),
                            (2, "Integer"),
                            (3, "Email"),
                            (4, "Time"),
                            (5, "Date"),
                            (6, "Text"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Archived")], default=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_setting",
            },
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_symptoms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_symptom",
            },
        ),
        migrations.CreateModel(
            name="TherapistEarning",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("amount", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "mimblu_earning",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("completed_booking", models.IntegerField(default=0)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[(1, "Subscription Plan"), (2, "Video Plan")], default=0
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapist_earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_therapist_earning",
            },
        ),
        migrations.CreateModel(
            name="UserSymptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_symptoms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_symptoms",
                        to="core.symptom",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_user_symptom",
            },
        ),
        migrations.CreateModel(
            name="VideoCoupon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("amount", models.CharField(max_length=16)),
                ("plan_id", models.CharField(blank=True, max_length=255, null=True)),
                ("min_amount", models.CharField(blank=True, max_length=16, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("valid_till", models.DateTimeField(blank=True, null=True)),
                ("limit", models.IntegerField(default=1)),
                ("user_limit", models.IntegerField(default=1)),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[(1, "Flat"), (2, "Percentage")], default=1
                    ),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_video_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_video_coupon",
            },
        ),
        migrations.CreateModel(
            name="VideoPlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("image_file", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("video_description", models.TextField(blank=True, null=True)),
                (
                    "currency_code",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("discounted_price", models.CharField(max_length=16)),
                ("total_price", models.CharField(max_length=16)),
                ("tax_price", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "tax_percentage",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("final_price", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "doctor_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("gross_price_per_video", models.CharField(max_length=16)),
                ("net_price_per_video", models.CharField(max_length=16)),
                ("credit", models.IntegerField()),
                (
                    "is_recommended",
                    models.SmallIntegerField(
                        choices=[(0, "No"), (1, "Yes")], default=0
                    ),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_video_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_video_plan",
            },
        ),
        migrations.CreateModel(
            name="SubscribedVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "doctor_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("coupon", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "coupon_discount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "plan_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gst_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("contact", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                (
                    "type_id",
                    models.SmallIntegerField(
                        choices=[(1, "Yes"), (2, "No")], default=2
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribed_videos",
                        to="core.videoplan",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_subscribed_video",
            },
        ),
        migrations.CreateModel(
            name="CouponUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscribed_video_id", models.IntegerField()),
                ("coupon_code", models.CharField(max_length=255)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "New"), (1, "Active"), (2, "Deleted")], default=1
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_coupons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_users",
                        to="core.videocoupon",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_coupon_uses",
                        to="core.videoplan",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_coupon_user",
            },
        ),
    ]
