# Generated by Django 6.0.2 on 2026-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_faq_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plan_name', models.TextField(blank=True, null=True)),
                ('plan_description', models.TextField(blank=True, null=True)),
                ('plan_weekly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plan_duration', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('doctor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_free_trial_days', models.IntegerField(blank=True, null=True)),
                ('plan_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_subscription_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeUserSelectedTherapistPlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('therapist_id', models.BigIntegerField()),
                ('plan_id', models.BigIntegerField()),
                ('selected_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_selected_therapist_plan',
                'managed': False,
            },
        ),
    ]
