# Generated by Django 6.0.2 on 2026-06-16 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nodesubscriptionplan_nodeuserselectedtherapistplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ChatsHistory',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('user_id', models.IntegerField(blank=True, null=True)),
                        ('chats_message', models.TextField(blank=True, null=True)),
                        ('created_on', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'tbl_chats_history',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='DailyCheckinAnswer',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('question_id', models.IntegerField(blank=True, null=True)),
                        ('answer', models.TextField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'tbl_daily_checkin_answer',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='DailyCheckinQuestion',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('question', models.TextField(blank=True, null=True)),
                        ('is_active', models.IntegerField(default=1)),
                    ],
                    options={
                        'db_table': 'tbl_daily_checkin_question',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='HomeCard',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('title', models.CharField(blank=True, max_length=255, null=True)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('img_url_path', models.CharField(blank=True, max_length=255, null=True)),
                        ('is_active', models.IntegerField(default=1)),
                        ('position', models.IntegerField(default=0)),
                        ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                    ],
                    options={
                        'db_table': 'tbl_home_card',
                        'managed': True,
                    },
                ),
                migrations.AlterModelOptions(
                    name='nodesubscriptionplan',
                    options={'managed': True},
                ),
                migrations.AlterModelOptions(
                    name='nodeuserselectedtherapistplan',
                    options={'managed': True},
                ),
                migrations.CreateModel(
                    name='ApiAccessToken',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('device_token', models.CharField(blank=True, max_length=255, null=True)),
                        ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='api_access_tokens', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'tbl_api_access_token',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='DailyCheckinQuestionAndAnswer',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('qna_map', models.JSONField(blank=True, null=True)),
                        ('entry_date', models.DateField(auto_now_add=True)),
                        ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_qnas', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'tbl_daily_checkin_question_and_answer',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='DailyJournal',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('entry_date', models.DateField(auto_now_add=True)),
                        ('journal', models.TextField(blank=True, null=True)),
                        ('question_id', models.IntegerField(blank=True, null=True)),
                        ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='daily_journals', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'tbl_daily_journal',
                        'managed': True,
                    },
                ),
                migrations.CreateModel(
                    name='UserAppReview',
                    fields=[
                        ('id', models.AutoField(primary_key=True, serialize=False)),
                        ('rating', models.IntegerField(blank=True, null=True)),
                        ('review', models.TextField(blank=True, null=True)),
                        ('created_by', models.ForeignKey(db_column='created_by_id', on_delete=django.db.models.deletion.CASCADE, related_name='app_reviews', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'tbl_user_app_review',
                        'managed': True,
                    },
                ),
            ],
            database_operations=[]
        )
    ]
