# Generated by Django 6.0.2 on 2026-06-19 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_chatshistory_dailycheckinanswer_dailycheckinquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycheckinanswer",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="dailycheckinanswer",
            name="journal_question_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dailycheckinanswer",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailycheckinquestion",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
