# Generated by Django 6.0.2 on 2026-06-20 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_dailycheckinanswer_created_on_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapistApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=255)),
                ("contact_no", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=128)),
                ("experience", models.CharField(max_length=64)),
                ("qualification", models.CharField(max_length=128)),
                ("rci_registered", models.CharField(max_length=16)),
                ("employment_status", models.CharField(max_length=128)),
                ("modalities", models.TextField()),
                ("hours_available", models.CharField(max_length=128)),
                ("days_available", models.CharField(max_length=128)),
                ("motivation", models.TextField()),
                ("distress_situation", models.TextField()),
                ("resume_file", models.CharField(max_length=1024)),
                (
                    "certifications_file",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "linkedin_profile",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[
                            (0, "New"),
                            (1, "Accept"),
                            (2, "Reject"),
                            (3, "Added"),
                        ],
                        default=0,
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_therapist_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_therapist_application",
            },
        ),
    ]
