# Generated by Django 6.0.2 on 2026-06-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_therapistapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="therapistapplication",
            name="city",
        ),
        migrations.AddField(
            model_name="therapistapplication",
            name="address",
            field=models.CharField(default="", max_length=512),
            preserve_default=False,
        ),
    ]
