# Generated by Django 6.0.2 on 2026-06-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_therapistapplication_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapistapplication",
            name="consent_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="therapistapplication",
            name="consent_given",
            field=models.BooleanField(default=False),
        ),
    ]
