# Generated by Django 6.0.2 on 2026-06-21 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_therapistapplication_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apiaccesstoken",
            name="access_token",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="apiaccesstoken",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="apiaccesstoken",
            name="device_name",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="apiaccesstoken",
            name="device_type",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="apiaccesstoken",
            name="type_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="apiaccesstoken",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_column="created_by_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_access_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="apiaccesstoken",
            name="device_token",
            field=models.CharField(default="", max_length=256),
        ),
    ]
