# Generated by Django 6.0.2 on 2026-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_apiaccesstoken_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistapplication",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
