# Generated by Django 6.0.2 on 2026-06-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_therapistapplication_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistapplication",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
