# Generated by Django 6.0.2

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_therapistapplication_name'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS tbl_subscription_plan (
                id bigserial PRIMARY KEY,
                plan_name text,
                plan_description text,
                plan_weekly_price numeric(10, 2),
                plan_duration integer,
                total_price numeric(10, 2),
                doctor_price numeric(10, 2),
                no_of_free_trial_days integer,
                plan_type text
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS tbl_subscription_plan;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS tbl_user_selected_therapist_plan (
                id bigserial PRIMARY KEY,
                user_id bigint NOT NULL,
                therapist_id bigint NOT NULL,
                plan_id bigint NOT NULL,
                selected_on timestamp with time zone
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS tbl_user_selected_therapist_plan;"
        ),
    ]
