# Generated by Django 6.0.2 on 2026-06-28 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_therapistapplication_state_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyjournal",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
