# Generated by Django 6.0.2 on 2026-06-28 12:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_dailyjournal_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyjournal",
            name="entry_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
