# Generated by Django 6.0.2 on 2026-06-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_dailyjournal_entry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailycheckinquestion",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
