# Generated by Django 6.0.2 on 2026-07-18 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_dailycheckinquestion_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Active")], default=1
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "db_table": "tbl_language",
            },
        ),
        migrations.AddField(
            model_name="therapistapplication",
            name="symptoms",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="therapistapplication",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="therapist_applications",
                to="core.language",
            ),
        ),
        migrations.CreateModel(
            name="TherapistInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("token", models.UUIDField(default=None, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used", models.BooleanField(default=False)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_therapist_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Therapist Invite",
                "verbose_name_plural": "Therapist Invites",
                "db_table": "tbl_therapist_invite",
            },
        ),
    ]
