# Generated by Django 6.0.2 on 2026-07-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_language_therapistapplication_symptoms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistapplication',
            name='rci_file',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
