# Generated by Django 6.0.2 on 2026-08-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_nodesubscriptionplan_unmanaged"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("meta_description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(default="Mental Wellness", max_length=100),
                ),
                (
                    "author",
                    models.CharField(default="Spilbloo Clinical Team", max_length=100),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        default="Dr. Ananya Sharma, RCI Registered Clinical Psychologist",
                        max_length=255,
                    ),
                ),
                ("date", models.CharField(default="August 2026", max_length=50)),
                ("read_time", models.CharField(default="6 min read", max_length=50)),
                ("featured", models.BooleanField(default=False)),
                ("image", models.URLField(blank=True, max_length=1024, null=True)),
                ("excerpt", models.TextField()),
                ("intro", models.TextField()),
                ("content_json", models.TextField(blank=True, null=True)),
                ("faqs_json", models.TextField(blank=True, null=True)),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[(0, "Inactive"), (1, "Published"), (2, "Draft")],
                        default=1,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "db_table": "tbl_blog_post",
                "ordering": ["-created_on"],
            },
        ),
    ]
