# Generated by Django 6.0.2 on 2026-08-08 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_blogpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="read_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
