# Generated by Django 6.0.2 on 2026-08-09 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_blogpost_date_alter_blogpost_read_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('users', models.TextField(blank=True, null=True)),
                ('from_id', models.IntegerField(blank=True, null=True)),
                ('to_id', models.IntegerField(blank=True, null=True)),
                ('readers', models.TextField(blank=True, null=True)),
                ('from_role', models.IntegerField(blank=True, null=True)),
                ('to_role', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_read', models.IntegerField(default=0)),
                ('notified_users', models.TextField(blank=True, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('state_id', models.IntegerField(default=1)),
                ('type_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_chat',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='ChatsHistory',
        ),
    ]
