# Generated by Django 6.0.2 on 2026-02-21 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type_id', models.IntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('no_of_free_trial_days', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('user_limit', models.IntegerField(default=1)),
                ('state_id', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_coupon',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('plan_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('no_of_video_session', models.IntegerField(default=0)),
                ('no_of_free_trial_days', models.IntegerField(default=0)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration', models.IntegerField(default=30)),
                ('plan_type', models.IntegerField(default=1)),
                ('type_id', models.IntegerField(default=1)),
                ('state_id', models.IntegerField(default=1)),
                ('is_recommended', models.IntegerField(default=0)),
                ('incentive_days', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tbl_plan',
            },
        ),
        migrations.CreateModel(
            name='SubscribedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.IntegerField(default=1)),
                ('state_id', models.IntegerField(default=1)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
                ('coupon_free_trial_days', models.IntegerField(default=0)),
                ('type_id', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('upcoming_plan_id', models.IntegerField(blank=True, null=True)),
                ('upcoming_state', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_plans', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
            ],
            options={
                'db_table': 'tbl_subscribed_plan',
            },
        ),
    ]
