# Generated by Django 5.2.6 on 2026-03-10 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedplan",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
