# Generated by Django 6.0.2 on 2026-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_coupon_valid_till_plan_doctor_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="video_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
