# Generated by Django 6.0.2 on 2026-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_subscribedplan_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedplan",
            name="incentive_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="no_of_video_session",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="offer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="rezorpay_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="signature",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="trial_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="zipcode",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
