# Generated by Django 6.0.2 on 2026-07-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_plan_video_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("data", models.TextField(blank=True, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tbl_subscription_webhook_log",
            },
        ),
    ]
