# Generated by Django 6.0.2 on 2026-03-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_subscribedplan_incentive_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscribedplan",
            name="renewal_date",
        ),
        migrations.RemoveField(
            model_name="subscribedplan",
            name="rezorpay_start_time",
        ),
    ]
