# Generated by Django 6.0.2 on 2026-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_webhooklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedplan",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
