# Generated by Django 6.0.2 on 2026-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0005_subscribedplan_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="discounted_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscribedplan",
            name="coupon_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
