# Generated by Django 6.0.2 on 2026-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_discounted_price_subscribedplan_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.IntegerField(choices=[(0, 'Paid Plan'), (1, 'Free Plan'), (2, 'Company Plan'), (3, 'One Time Payment Plan')], default=0),
        ),
        migrations.AlterField(
            model_name='subscribedplan',
            name='plan_type',
            field=models.IntegerField(choices=[(0, 'Razorpay Subscription'), (1, 'Free Subscription'), (2, 'Company Subscription'), (3, 'One Time Payment Subscription')], default=0),
        ),
        migrations.AlterField(
            model_name='subscribedplan',
            name='state_id',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Deleted'), (3, 'Upcoming'), (4, 'Expired'), (5, 'Canceled'), (6, 'Incomplete'), (7, 'Immediate Cancel'), (8, 'Payment Pending'), (9, 'Payment Halt')], default=1),
        ),
        migrations.AlterField(
            model_name='subscribedplan',
            name='upcoming_state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Deleted'), (3, 'Upcoming'), (4, 'Expired'), (5, 'Canceled'), (6, 'Incomplete'), (7, 'Immediate Cancel'), (8, 'Payment Pending'), (9, 'Payment Halt')], default=1),
        ),
    ]
