# Generated by Django 6.0.2 on 2026-02-21 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.SmallIntegerField(blank=True, null=True)),
                ("about_me", models.TextField(blank=True, null=True)),
                ("contact_no", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                ("language", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profile_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tos", models.SmallIntegerField(default=0)),
                (
                    "role_id",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Admin"),
                            (1, "Manager"),
                            (2, "User"),
                            (3, "Client"),
                            (4, "Patient"),
                            (5, "Doctor"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Inactive"),
                            (1, "Active"),
                            (2, "Banned"),
                            (3, "Deleted"),
                        ],
                        default=1,
                    ),
                ),
                ("type_id", models.SmallIntegerField(default=0)),
                ("last_visit_time", models.DateTimeField(blank=True, null=True)),
                ("last_action_time", models.DateTimeField(blank=True, null=True)),
                ("last_password_change", models.DateTimeField(blank=True, null=True)),
                ("login_error_count", models.IntegerField(default=0)),
                (
                    "activation_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timezone", models.CharField(blank=True, max_length=100, null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_user",
            },
        ),
    ]
