# Generated by Django 5.2.4 on 2026-02-21 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="HaLogins",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id_str", models.CharField(db_column="user_id", max_length=50)),
                ("login_provider", models.CharField(max_length=50)),
                ("login_provider_identifier", models.CharField(max_length=100)),
                ("created_by_id", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id_fk",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ha_logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ha_logins",
            },
        ),
    ]
