# Generated by Django 6.0.2 on 2026-06-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_halogins_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.CharField(blank=True, default='no', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
