# Generated by Django 5.2.6 on 2026-03-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_halogins_id_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="doctor_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
