# Generated by Django 6.0.2 on 2026-06-19 17:23

import sys
from django.db import migrations, models

# In test environments (SQLite), we must run DDL operations because the test DB is created from scratch.
# In dev/prod environments (Postgres), the columns already exist, so we skip DDL operations.
is_test = "test" in sys.argv

state_ops = [
    migrations.AddField(
        model_name="user",
        name="age_group",
        field=models.CharField(blank=True, max_length=16, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="consent_accepted_on",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="designation",
        field=models.IntegerField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="doctor_assigned_time",
        field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="doctor_id",
        field=models.IntegerField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="email_enabled",
        field=models.SmallIntegerField(blank=True, default=1, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="email_verified",
        field=models.SmallIntegerField(blank=True, default=0, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="is_consent_accept",
        field=models.IntegerField(blank=True, default=0, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="otp",
        field=models.IntegerField(blank=True, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="otp_verified",
        field=models.IntegerField(blank=True, default=0, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="push_enabled",
        field=models.SmallIntegerField(blank=True, default=1, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="therapist_gender",
        field=models.IntegerField(blank=True, default=0, null=True),
    ),
    migrations.AddField(
        model_name="user",
        name="video_credit",
        field=models.CharField(blank=True, default="0", max_length=16, null=True),
    ),
]

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_experience_user_is_available_user_online_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_ops,
            database_operations=state_ops
        )
    ]
