# Generated by Django 5.2.6 on 2026-03-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_doctor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "Other"),
                    (1, "Male"),
                    (2, "Female"),
                    (3, "Transgender Male"),
                    (4, "Transgender Female"),
                    (5, "Gender Queer"),
                    (6, "Non Binary"),
                ],
                default=0,
                null=True,
            ),
        ),
    ]
