# Generated by Django 5.2.6 on 2026-03-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_gender"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="halogins",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id_fk",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ha_logins",
                to="accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="accounts_user_set",
                related_query_name="user",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="accounts_user_permissions_set",
                related_query_name="user",
                to="auth.permission",
            ),
        ),
    ]
