# Generated by Django 6.0.2 on 2026-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_age_group_user_consent_accepted_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sessions_completed",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
