# Generated by Django 6.0.2 on 2026-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_halogins_user_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_notify",
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="video_credit",
            field=models.IntegerField(default=0),
        ),
    ]
