# Generated by Django 6.0.2 on 2026-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_sessions_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_hidden_from_directory",
            field=models.BooleanField(default=False),
        ),
    ]
