# Generated by Django 6.0.2 on 2026-08-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_is_hidden_from_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletion_requested_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deletion_scheduled_purge_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
