# Generated by Django 6.0.2 on 2026-09-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(
                blank=True,
                default="+91",
                help_text="Phone dial code e.g. +91, +1, +44",
                max_length=16,
                null=True,
            ),
        ),
    ]
