# Generated by Django 6.0.2 on 2026-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_normalize_contact_no_e164"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
