# Generated by Django 6.0.2 on 2026-09-07 12:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name e.g. MSG91 Production", max_length=128
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("msg91", "MSG91 (SMS & OTP)"),
                            ("whatsapp_cloud", "Meta WhatsApp Cloud API"),
                            ("aws_ses", "AWS SES (Email)"),
                            ("smtp", "SMTP (Email)"),
                            ("aws_sns", "AWS SNS (SMS)"),
                            ("firebase", "Firebase Cloud Messaging (FCM)"),
                            ("console", "Console / Mock Testing"),
                        ],
                        max_length=64,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, help_text="Priority ordering (1 is highest priority)"
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Gateway configuration JSON (e.g. auth_key, sender_id, api_token, timeout, etc.)",
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "fallback_gateway",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional fallback gateway if this gateway encounters an error",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fallback_for",
                        to="communication.communicationgateway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gateway / Provider",
                "verbose_name_plural": "Gateways & Providers",
                "db_table": "tbl_communication_gateway",
                "ordering": ["channel", "priority", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_code",
                    models.CharField(
                        db_index=True,
                        help_text="Event trigger key e.g. AUTH_OTP, BOOKING_CONFIRMATION, SESSION_REMINDER",
                        max_length=64,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Template title for administrative reference",
                        max_length=128,
                    ),
                ),
                (
                    "external_template_id",
                    models.CharField(
                        blank=True,
                        help_text="Gateway/DLT Template ID (e.g. MSG91 template ID 6a9d6a75b3e1cb31640825e3 or WhatsApp template name)",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "sender_override",
                    models.CharField(
                        blank=True,
                        help_text="Custom Sender ID/Header (e.g. SPBLOO) overriding gateway default",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True,
                        help_text="Email Subject line or Push notification title. Supports {{variables}}.",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="Message body. Supports {{variable}} or ##variable## dynamic placeholders."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message Template",
                "verbose_name_plural": "Message Templates",
                "db_table": "tbl_communication_template",
                "unique_together": {("event_code", "channel")},
            },
        ),
        migrations.CreateModel(
            name="CommunicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        db_index=True,
                        help_text="Recipient phone number, email address, or device token",
                        max_length=256,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("push", "Push Notification"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("event_code", models.CharField(db_index=True, max_length=64)),
                (
                    "rendered_subject",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("rendered_body", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent / Dispatched"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "external_message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Gateway transaction ID (e.g. MSG91 request_id, SES MessageId)",
                        max_length=256,
                        null=True,
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("gateway_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="communication.communicationgateway",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communication_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="communication.communicationtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Log",
                "verbose_name_plural": "Delivery Logs",
                "db_table": "tbl_communication_log",
                "ordering": ["-created_on"],
            },
        ),
    ]
