# Generated by Django 5.2.4 on 2026-02-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("state_id", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "tbl_slot",
            },
        ),
        migrations.CreateModel(
            name="DoctorSlot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("availability_slot_id", models.IntegerField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("state_id", models.IntegerField(default=1)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_doctor_slot",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("to_user_id", models.IntegerField()),
                ("model_type", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_notification",
            },
        ),
        migrations.CreateModel(
            name="SlotBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_id", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("doctor_id", models.IntegerField()),
                ("state_id", models.IntegerField(default=2)),
                ("type_id", models.IntegerField(default=0)),
                ("is_active", models.IntegerField(default=0)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_refunded", models.IntegerField(default=0)),
                ("doctor_reschedule", models.IntegerField(default=0)),
                ("patient_reschedule", models.IntegerField(default=0)),
                ("old_start_time", models.DateTimeField(blank=True, null=True)),
                ("old_end_time", models.DateTimeField(blank=True, null=True)),
                ("is_reschedule_confirm", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_slot_booking",
            },
        ),
    ]
