# Generated by Django 6.0.2 on 2026-04-13 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('email_domain', models.CharField(max_length=64, unique=True)),
                ('image_file', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=16, null=True)),
                ('contact', models.CharField(blank=True, max_length=32, null=True)),
                ('plan_id', models.CharField(blank=True, max_length=255, null=True)),
                ('state_id', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Deleted')], default=1)),
                ('type_id', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_company',
            },
        ),
        migrations.CreateModel(
            name='CompanyCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('plan_id', models.IntegerField()),
                ('no_of_free_trial_days', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0)),
                ('user_limit', models.IntegerField(default=1)),
                ('coupon_type', models.IntegerField(choices=[(1, 'Unlimited Period'), (2, 'Limited Period')], default=1)),
                ('state_id', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Deleted'), (3, 'Cancelled')], default=1)),
                ('valid_till', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('one_day_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('no_of_video_session', models.IntegerField(default=0)),
                ('invoice_plan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='company.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_coupons_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_company_coupon',
            },
        ),
        migrations.CreateModel(
            name='MonthlyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('coupon_code', models.CharField(max_length=255)),
                ('state_id', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Initiated'), (2, 'Deleted')], default=0)),
                ('type_id', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_invoices', to='company.company')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_invoices', to='company.companycoupon')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_invoices_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_company_monthly_invoice',
            },
        ),
        migrations.CreateModel(
            name='CouponInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField()),
                ('coupon_code', models.CharField(max_length=255)),
                ('one_subscription_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscription_count', models.IntegerField(default=0)),
                ('subscription_days', models.IntegerField(default=0)),
                ('state_id', models.SmallIntegerField(choices=[(0, 'New'), (1, 'Active'), (2, 'Deleted')], default=0)),
                ('type_id', models.IntegerField(default=0)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_invoices', to='company.company')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_invoices', to='company.companycoupon')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('monthly_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_invoices', to='company.monthlyinvoice')),
            ],
            options={
                'db_table': 'tbl_company_coupon_invoice',
            },
        ),
    ]
