# Generated by Django 6.0.2 on 2026-08-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companycouponuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycouponuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
