# Generated by Django 6.0.2 on 2026-08-22 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoveryBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_booking_id", models.IntegerField(blank=True, null=True)),
                ("date", models.DateField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, default=299, max_digits=8),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=199, max_digits=8),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("refund_eligible_until", models.DateTimeField(blank=True, null=True)),
                ("refund_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "refunded_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "state_id",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Created"),
                            (1, "Paid"),
                            (2, "Canceled"),
                            (3, "Completed"),
                            (4, "Refunded"),
                            (5, "Refund Failed"),
                        ],
                        default=0,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_bookings_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discovery_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_discovery_booking",
            },
        ),
    ]
