# Generated by Django 6.0.2 on 2026-08-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discover", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoverybooking",
            name="is_no_show",
            field=models.BooleanField(default=False),
        ),
    ]
